# Base Image

FROM node:18-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install && npm run build


# Below is the code for stage2[for Dockerfile code optimization]

#FROM gcr.io/distroless/nodejs22-debian12

#WORKDIR /app

#COPY --from=builder /app .

EXPOSE 3000

CMD ["npm","run","dev","--","--port","3000","--host","0.0.0.0"]
